---
title: "Find Aliivibrio"
author: "Dave Edison Rojas Calderon"
date: "2023-07-12"
output: html_document
---

Load packages
```{r}
library(tidyverse)
library(stringr)
library(tidyr)
library(fs)
library(dplyr)
library(ggplot2)
library(Compositional)
library(broom)  # devtools::install_github("tidymodels/broom")
library(cowplot)
library(janitor)
library(qiime2R)
library(factoextra)
library(readxl)
library(vegan)
library(patchwork)
```

Load data
```{r}
# SVs
SVs = read_qza(file = "../data/salmon-5/table-atlanticsalmon-5.qza")

# Taxonomy assignations
taxonomy = read_qza(file = "../data/salmon-5/tax-class-atlanticsalmon-5.qza")

# Metadata
metadata = read_q2metadata("../data/salmon-5/metadata.tsv") %>% 
  mutate(phase2 = phase) %>% 
  mutate(WP2 = WP)

metadata = metadata %>% 
  mutate(SampleID = str_replace_all(SampleID, "-", ".")) %>% 
  mutate(phase2 = str_replace(phase2, "C0", "Observation")) %>% 
  mutate(phase2 = str_replace(phase2, "C1", "Intervention")) %>%
  mutate(WP2 = str_replace(WP2, "6A", "Wild")) %>% 
  mutate(WP2 = str_replace(WP2, "5A", "Farm")) %>% 
  rename(sample = SampleID)

meta = metadata %>% 
  select(sample, phase, phase2, WP, WP2, sample_group, country, timepoint, sample_dim, type_sample)
```

Clean and transform into a table
```{r}
# SVs table
SVs = SVs$data %>% 
  data.frame() %>% 
  rownames_to_column(var = "Feature.ID")

# Taxonomy table
taxonomy = taxonomy$data %>% 
  parse_taxonomy()

# Add Unclassified if the row is empty
taxonomy[is.na(taxonomy)] = ""
taxonomy[taxonomy == "__"] = ""

for (i in 1:nrow(taxonomy)){
  if (taxonomy[i,7] != ""){
    taxonomy$Species[i] = paste(taxonomy$Genus[i], taxonomy$Species[i], sep = " ")
  } else if (taxonomy[i,2] == ""){
    kingdom = paste("Unclassified", taxonomy[i,1], sep = " ")
    taxonomy[i, 2:7] = kingdom
  } else if (taxonomy[i,3] == ""){
    phylum = paste("Unclassified", taxonomy[i,2], sep = " ")
    taxonomy[i, 3:7] = phylum
  } else if (taxonomy[i,4] == ""){
    class = paste("Unclassified", taxonomy[i,3], sep = " ")
    taxonomy[i, 4:7] = class
  } else if (taxonomy[i,5] == ""){
    order = paste("Unclassified", taxonomy[i,4], sep = " ")
    taxonomy[i, 5:7] = order
  } else if (taxonomy[i,6] == ""){
    family = paste("Unclassified", taxonomy[i,5], sep = " ")
    taxonomy[i, 6:7] = family
  } else if (taxonomy[i,7] == ""){
    taxonomy$Species[i] = paste("Unclassified ",taxonomy$Genus[i], sep = " ")
  }
}

# Add previous taxonomy level when "unclassified
# Iterate over each row of the dataframe
for (i in 1:nrow(taxonomy)) {
  # Iterate over each column of the row
  for (j in 1:ncol(taxonomy)) {
    # Check if the value is "uncultured"
    if (taxonomy[i, j] == "uncultured") {
      # Update the value with "uncultured" followed by the previous column value
      taxonomy[i, j] = paste0("uncultured ", taxonomy[i, j - 1])
    }
  }
}

# Remove Eukaryota
taxonomy = taxonomy %>% 
  filter(Kingdom != "d__Eukaryota")

gc()
```

Select genus from taxonomy
```{r}
genus = taxonomy %>% 
  rownames_to_column(var = "Feature.ID") %>% 
  select(Feature.ID, Genus) %>% 
  right_join(SVs,
              by = "Feature.ID") %>% 
  select(!Feature.ID) %>% 
  drop_na() %>%
  group_by(Genus) %>% 
  summarise_all(list(sum)) %>% 
  pivot_longer(names_to = "sample",
               values_to = "Count",
               cols = -Genus) %>% 
  dplyr::select("sample", everything()) %>% 
  mutate(Genus = str_replace(Genus,
                              "Unclassified Unassigned",
                              "Unclassified"))
```

Join with metadata
```{r}
genus = genus %>% 
  left_join(meta,
            by = join_by(sample)) %>% 
  rename(Taxonomy = Genus)
```

Find Aliivibrio
```{r}
genus %>%
  filter(Taxonomy == "Aliivibrio") %>% 
  filter(Count > 0)
```

